// Bridges OpenNext's `CloudflareEnv` global to the bindings generated by
// `wrangler types` into worker-configuration.d.ts (run `npm run cf-typegen`
// after changing wrangler.jsonc). Runtime secrets are set via
// `wrangler secret put`, so they aren't in wrangler.jsonc and must be
// declared here.

interface CloudflareEnv extends Cloudflare.Env {
  /** HMAC key for signed session cookies (required in production). */
  SESSION_SECRET?: string;
  /** Google OAuth client; when unset, the passwordless dev login is enabled. */
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  /** Optional: enables LLM-resolved source names (falls back to a deterministic algorithm). */
  ANTHROPIC_API_KEY?: string;
  /** Optional bearer token guarding the /api/cron endpoint. */
  CRON_SECRET?: string;
  /** Force-enable dev login ("1"); otherwise on only when OAuth is unconfigured. */
  ALLOW_DEV_LOGIN?: string;
}
